### ISSUE TITLE
prune-empty: thread panicked

### ISSUE THREAD

**Issue by abitrolly** [heinrichti/gitrw#1]
```
$ RUST_BACKTRACE=1 ~/.cargo/bin/gitrw prune-empty
thread 'main' panicked at crates/gitrwlib/src/packreader.rs:215:10:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: gitrwlib::Repository::create
   4: gitrw::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1]    245108 IOT instruction (core dumped)  RUST_BACKTRACE=1 ~/.cargo/bin/gitrw prune-empty
```

Maybe it is possible to upload stable tagged version to test?

**Comment by heinrichti** [comment]
From what I can see I would guess you are not running it in a git mirror, but maybe in a workspace folder?
Instead of a tag you might as well give me the commit id, but as I haven't worked on it for a while I will just assume latest 😋

**Comment by abitrolly** [comment]
I am trying to remove empty commits from this PR https://github.com/containerd/nerdctl/pull/3138/commits/93a319bb33596026a8140b70382b89507f19efda and so far everything fails.

I do run `gitrw` from local clone.

**Comment by abitrolly** [comment]
Installed with `cargo install --git https://github.com/heinrichti/gitrw`.

**Comment by heinrichti** [comment]
This tool is not designed to work on a pull request basis. It will work on the whole repository, which you will have to check out with the --mirror flag. You really should not operate on a workspace. If you just need to remove a few commits from a pull request, it is better to use an interactive rebase, for example, not rewrite the whole repository to remove all empty commits.

**Comment by abitrolly** [comment]
Do you mean "remove by hand" using interactive rebase? Meaning manually going through revision log, writing down empty commits, and then marking them as "fixup". Sigh.

**Comment by abitrolly** [comment]
I do understand that this tool is only for filtering repos, and it can not filter a separate branch, so I have to use something else if I don't want to "remove by hand".

![quotes](https://github.com/user-attachments/assets/fabd35d0-10c7-41d9-92fb-68c9c9255c61)

**Comment by abitrolly** [comment]
Asked in https://www.reddit.com/r/git/comments/1e5mimp/git_rebase_empty_drop_force_upstreamman_doesnt/ - maybe people know why standard `git rebase --empty drop` doesn't work. This use case is too basic to require a separate tool.

**Comment by abitrolly** [comment]
OMG! As explained by the generous redditor @pig94, the solution was to use `--no-keep-empty`. :grin: 

```
git rebase --no-keep-empty -f upstream/main
```
